### ISSUE TITLE
GitHub pages deployment

### ISSUE THREAD

**Issue by faustM** [Lasten-Ernest/Lasten-Ernest.github.io#2]
Hi [@Lasten-Ernest ](https://github.lasten-ernest/),
Congratulations! tada
Your project is complete! There is nothing else to say other than... it's time to merge it rocket :

Cheers and Happy coding! clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by HatimDev-HE** [comment]
Hi @Lasten-Ernest,

**STATUS: APPROVED! 🥇 💯**

![congs gif](https://user-images.githubusercontent.com/102610715/173520252-be240a94-6fa6-4f25-b628-599b22a28b24.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 🚀
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Code Review by @HatimDev-HE**
